"""initial schema

Revision ID: 38262302f50b
Revises: 
Create Date: 2026-07-14 20:24:02.567588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38262302f50b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('entity_type', sa.Enum('alert', 'case', name='ai_entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('task', sa.Enum('summary', 'triage', 'steps', 'report', 'mitre', 'nl_search', name='ai_task'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analyses'))
    )
    op.create_index(op.f('ix_ai_analyses_entity_id'), 'ai_analyses', ['entity_id'], unique=False)
    op.create_table('automation_runs',
    sa.Column('trigger', sa.String(length=100), nullable=False),
    sa.Column('playbook', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='automation_status'), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_runs'))
    )
    op.create_table('mitre_techniques',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tactic', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mitre_techniques'))
    )
    op.create_index(op.f('ix_mitre_techniques_tactic'), 'mitre_techniques', ['tactic'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('assets',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('criticality', sa.Enum('low', 'medium', 'high', 'critical', name='asset_criticality'), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_assets_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_hostname'), 'assets', ['hostname'], unique=False)
    op.create_index(
        'ix_assets_hostname_trgm', 'assets', ['hostname'], unique=False,
        postgresql_using='gin', postgresql_ops={'hostname': 'gin_trgm_ops'},
    )
    op.create_table('integrations',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('virustotal', 'abuseipdb', 'shodan', 'wazuh', 'slack', 'discord', name='integration_kind'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_integrations_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations'))
    )
    op.create_table('iocs',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('ip', 'domain', 'hash', 'url', name='ioc_type'), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('reputation', sa.String(length=50), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_iocs_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_iocs')),
    sa.UniqueConstraint('org_id', 'value', name='uq_iocs_org_id_value')
    )
    op.create_index(op.f('ix_iocs_value'), 'iocs', ['value'], unique=False)
    op.create_index(
        'ix_iocs_value_trgm', 'iocs', ['value'], unique=False,
        postgresql_using='gin', postgresql_ops={'value': 'gin_trgm_ops'},
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('tags',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_tags_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('org_id', 'name', name='uq_tags_org_id_name')
    )
    op.create_table('users',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_users_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='alert_severity'), nullable=False),
    sa.Column('ai_severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='alert_ai_severity'), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('new', 'triaging', 'investigating', 'closed', 'false_positive', name='alert_status'), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=True),
    sa.Column('src_ip', postgresql.INET(), nullable=True),
    sa.Column('dst_ip', postgresql.INET(), nullable=True),
    sa.Column('host_asset_id', sa.UUID(), nullable=True),
    sa.Column('user_subject', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_asset_id'], ['assets.id'], name=op.f('fk_alerts_host_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_alerts_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_external_id'), 'alerts', ['external_id'], unique=False)
    op.create_index(op.f('ix_alerts_occurred_at'), 'alerts', ['occurred_at'], unique=False)
    op.create_index('ix_alerts_org_status_severity_occurred', 'alerts', ['org_id', 'status', 'severity', 'occurred_at'], unique=False)
    op.create_index('ix_alerts_search_vector', 'alerts', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('audit_logs',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_audit_logs_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('cases',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'investigating', 'contained', 'closed', name='case_status'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='case_severity'), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_cases_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_cases_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_cases_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    op.create_index(op.f('ix_cases_opened_at'), 'cases', ['opened_at'], unique=False)
    op.create_index('ix_cases_search_vector', 'cases', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_cases_status_opened_at', 'cases', ['status', 'opened_at'], unique=False)
    op.create_table('comments',
    sa.Column('entity_type', sa.Enum('alert', 'case', name='comment_entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index(op.f('ix_comments_entity_id'), 'comments', ['entity_id'], unique=False)
    op.create_table('enrichments',
    sa.Column('ioc_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], name=op.f('fk_enrichments_ioc_id_iocs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrichments')),
    sa.UniqueConstraint('ioc_id', 'provider', name='uq_enrichments_ioc_id_provider')
    )
    op.create_index(op.f('ix_enrichments_ioc_id'), 'enrichments', ['ioc_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('new_case', 'case_assigned', 'ai_report_ready', 'system', name='notification_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('saved_searches',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('query', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_searches_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_searches'))
    )
    op.create_index(op.f('ix_saved_searches_user_id'), 'saved_searches', ['user_id'], unique=False)
    op.create_table('taggables',
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_taggables_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'entity_type', 'entity_id', name=op.f('pk_taggables'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('alert_events',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_events_alert_id_alerts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_events'))
    )
    op.create_index(op.f('ix_alert_events_alert_id'), 'alert_events', ['alert_id'], unique=False)
    op.create_table('alert_iocs',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('ioc_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_iocs_alert_id_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], name=op.f('fk_alert_iocs_ioc_id_iocs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', 'ioc_id', name=op.f('pk_alert_iocs'))
    )
    op.create_table('alert_mitre',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('source', sa.Enum('ai', 'rule', 'analyst', name='mitre_mapping_source'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_mitre_alert_id_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['mitre_techniques.id'], name=op.f('fk_alert_mitre_technique_id_mitre_techniques'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', 'technique_id', name=op.f('pk_alert_mitre'))
    )
    op.create_table('case_alerts',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_case_alerts_alert_id_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_alerts_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'alert_id', name=op.f('pk_case_alerts'))
    )
    op.create_table('reports',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.Enum('markdown', 'pdf', name='report_format'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_reports_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_reports_generated_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_case_id'), 'reports', ['case_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_timeline_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_timeline_events_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events'))
    )
    op.create_index(op.f('ix_timeline_events_case_id'), 'timeline_events', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_events_case_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_reports_case_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('case_alerts')
    op.drop_table('alert_mitre')
    op.drop_table('alert_iocs')
    op.drop_index(op.f('ix_alert_events_alert_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_table('user_roles')
    op.drop_table('taggables')
    op.drop_index(op.f('ix_saved_searches_user_id'), table_name='saved_searches')
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_enrichments_ioc_id'), table_name='enrichments')
    op.drop_table('enrichments')
    op.drop_index(op.f('ix_comments_entity_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_cases_status_opened_at', table_name='cases')
    op.drop_index('ix_cases_search_vector', table_name='cases', postgresql_using='gin')
    op.drop_index(op.f('ix_cases_opened_at'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_alerts_search_vector', table_name='alerts', postgresql_using='gin')
    op.drop_index('ix_alerts_org_status_severity_occurred', table_name='alerts')
    op.drop_index(op.f('ix_alerts_occurred_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_external_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('role_permissions')
    op.drop_index('ix_iocs_value_trgm', table_name='iocs', postgresql_using='gin')
    op.drop_index(op.f('ix_iocs_value'), table_name='iocs')
    op.drop_table('iocs')
    op.drop_table('integrations')
    op.drop_index('ix_assets_hostname_trgm', table_name='assets', postgresql_using='gin')
    op.drop_index(op.f('ix_assets_hostname'), table_name='assets')
    op.drop_table('assets')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_mitre_techniques_tactic'), table_name='mitre_techniques')
    op.drop_table('mitre_techniques')
    op.drop_table('automation_runs')
    op.drop_index(op.f('ix_ai_analyses_entity_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
